; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32c3]
extends = env:esp32c3_base
build_flags =
    ${env:esp32c3_base.build_flags}
    ${serial.build_flags}
    ${wifi.build_flags}
extra_scripts =
    ${env:esp32c3_base.extra_scripts}
    ${wifi.extra_scripts}
lib_deps =
    ${env:esp32c3_base.lib_deps}
    ${wifi.lib_deps}

[env:esp32c3_base]
board = esp32-c3-devkitm-1
board_build.f_cpu = 160000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = huge_app.csv
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DUSE_ESP32
    -DUSE_ESP32_FRAMEWORK_ARDUINO
    -DAUDIO_NO_SD_FS
    -DTEMPLATE_PLACEHOLDER=36
    -DSTARTUP_BOOST
extra_scripts =
    pre:make_version.py
    post:merge_firmware.py
framework = arduino
lib_deps=
    EEPROM
    https://github.com/RobTillaart/CRC @ ^1.0.2
monitor_speed = 115200
platform = https://github.com/platformio/platform-espressif32.git
upload_protocol = esptool

[env:esp32c3_ota]
extends = env:esp32c3
upload_protocol = espota

[env:esp32c3_serial]
build_flags =
    ${env:esp32c3_base.build_flags}
    ${serial.build_flags}
extends = env:esp32c3_base

[env:esp32c3_wifi]
build_flags =
    ${env:esp32c3_base.build_flags}
    ${wifi.build_flags}
extends = env:esp32c3_base
extra_scripts =
    ${env:esp32c3_base.extra_scripts}
    ${wifi.extra_scripts}
lib_deps =
    ${env:esp32c3_base.lib_deps}
    ${wifi.lib_deps}

[platformio]
default_envs = esp32c3

[serial]
build_flags =
    -DSERIAL_ENABLE

[wifi]
build_flags =
    -DWIFI_ENABLE
extra_scripts =
    pre:minify_data.py
    pre:embed_data.py
lib_deps =
    ESPmDNS @ 2.0.0
    WiFi
    https://github.com/esphome/ESPAsyncWebServer @ ^3.2.2
    https://github.com/tzapu/WiFiManager.git
    
